// Workout data - edit sets, reps, and exercises here.
const days = [
  { id:1, kind:"push", focus:"Push A", muscles:"Chest · Shoulders · Triceps", ex:[
    {n:"Incline dumbbell press", s:"3 × 10–12", g:{t:"Upper chest, front delts, triceps", r:"75s",
      steps:["Low incline (~30°), dumbbells at shoulder height, elbows ~45°.","Press up and slightly in, without locking out.","Lower with control to a stretch across the upper chest."],
      cue:"Drive through the chest, not the shoulders. Elbows don't flare wide."}},
    {n:"Seated shoulder press", s:"3 × 10–12", g:{t:"Front + side delts, triceps", r:"75s",
      steps:["Back supported, handles at shoulder height.","Press up to near lockout.","Lower under control to shoulder height."],
      cue:"Keep your lower back on the pad; don't arch to press."}},
    {n:"Flat chest press (machine)", s:"3 × 10–12", g:{t:"Chest, front delts, triceps", r:"75s",
      steps:["Handles level with mid-chest, shoulder blades back.","Press forward to near-lockout, squeezing the chest.","Return slowly to a light stretch."],
      cue:"Elbows drive toward each other, not just your hands forward."}},
    {n:"Cable / machine chest fly", s:"2 × 12–15", g:{t:"Chest", r:"45s",
      steps:["Handles at chest height, soft elbow bend.","Sweep hands together in a wide arc.","Open back out slowly to a stretch."],
      cue:"Fixed elbow angle throughout; it's a hug, not a press."}},
    {n:"Dumbbell lateral raises", s:"4 × 12–15", star:true, g:{t:"Side delts", r:"45s",
      steps:["Light dumbbells at your sides, slight forward lean.","Raise to shoulder height, leading with elbows.","Lower slowly, resisting the whole way."],
      cue:"Pinkie slightly higher than thumb. Go lighter than feels right; swinging means too heavy."}},
    {n:"Triceps rope pushdown", s:"3 × 12–15", g:{t:"Triceps", r:"45s",
      steps:["Elbows pinned at your sides.","Push down and apart to full extension.","Let the rope rise under control."],
      cue:"Only your forearms move."}},
    {n:"Incline fast walk", s:"10 min", tag:"finisher", g:{t:"Conditioning", r:"-",
      steps:["Treadmill on a noticeable incline, brisk pace."],
      cue:"Add incline before speed; knee-friendly and burns well."}},
  ]},
  { id:2, kind:"pull", focus:"Pull A", muscles:"Back · Rear delts · Biceps", ex:[
    {n:"Close-grip lat pulldown (V-bar)", s:"3 × 10–12", g:{t:"Lats, biceps", r:"75s",
      steps:["V-bar attachment, hands close together in a neutral grip.","Pull down to your lower chest, elbows tracking down and back.","Control back up to a full stretch overhead."],
      cue:"Drive your elbows down past your ribs; let your lats do the pulling, not just your arms."}},
    {n:"Seated cable row", s:"3 × 10–12", g:{t:"Mid-back, rear delts", r:"75s",
      steps:["Feet braced, tall back, arms extended.","Pull to your belly button, elbows back.","Extend slowly, letting the blades stretch."],
      cue:"Move from your arms and shoulder blades, not your lower back rocking."}},
    {n:"Single-arm dumbbell row", s:"3 × 10–12 / side", g:{t:"Lats, mid-back", r:"60s",
      steps:["One knee and hand on the bench, back flat.","Row to your hip, elbow driving up and back.","Lower to a full stretch, then switch sides."],
      cue:"Pull toward your hip, elbow close to the body."}},
    {n:"Face pulls", s:"3 × 15, 12, 10", g:{t:"Rear delts, posture", r:"45s",
      steps:["Rope at face height, thumbs back.","Pull to your face, hands finishing by your ears.","Return slowly."],
      cue:"Finish elbows high, knuckles back, like a double-biceps pose."}},
    {n:"Dumbbell biceps curl", s:"2 × 10–12", g:{t:"Biceps", r:"45s",
      steps:["Elbows pinned at your sides.","Curl up, rotating palms toward your shoulders.","Lower fully under control."],
      cue:"Let the wrist rotate naturally. Shrugging or leaning back means too heavy."}},
    {n:"Incline walk or bike", s:"12–15 min", tag:"finisher", g:{t:"Conditioning", r:"-",
      steps:["Steady, brisk pace you can hold for the block."],
      cue:"Conversational pace: talking possible, singing isn't."}},
  ]},
  { id:3, kind:"legs", focus:"Legs A: Glute focus", muscles:"knee-aware", ex:[
    {n:"Barbell / Smith hip thrust", s:"4 × 10–12", star:true, g:{t:"Glutes, hamstrings", r:"90s",
      steps:["Upper back on a bench, bar over hips with a pad.","Drive through your heels to a flat tabletop position.","Squeeze glutes hard at the top, then lower."],
      cue:"Finish with a glute squeeze, not a lower-back arch. Reduce load if the left knee complains."}},
    {n:"Leg press", s:"3 × 12–15", g:{t:"Quads, glutes", r:"75s",
      steps:["Full back against the pad, feet hip-width.","Lower to a moderate ~90° depth.","Press through your heels, no knee lockout."],
      cue:"Higher foot placement shifts load toward the glutes and off the knee."}},
    {n:"Sumo goblet squat", s:"3 × 12–15", g:{t:"Adductors, glutes, quads", r:"60s",
      steps:["Dumbbell at your chest, wide stance, toes out.","Sit to a comfortable depth, knees tracking over toes.","Drive through the heels to stand."],
      cue:"Depth is optional for the left knee; control isn't."}},
    {n:"Barbell RDL (from a rack, hip height)", s:"3 × 10–12", g:{t:"Hamstrings, glutes", r:"90s",
      steps:["Bar starts at hip height from a rack, not a floor pull.","Push hips back, bar tracking close to your thighs.","Stretch to mid-shin, then drive hips forward to stand."],
      cue:"Hips to the wall, not bar to the floor. New implement, so start light for a session or two."}},
    {n:"Curtsy lunge (bodyweight or light DB)", s:"3 × 10–12 / side", g:{t:"Glute medius, adductors", r:"60s",
      steps:["Step one leg diagonally behind and across the other.","Lower straight down, front shin near-vertical.","Push through the front heel to stand."],
      cue:"New pattern for the left knee: bodyweight only at first, shallow range, stop short of any pinching."}},
    {n:"Standing calf raise", s:"3 × 15–20", g:{t:"Gastrocnemius", r:"45s",
      steps:["Balls of feet on a step, heels hanging off.","Lower for a full stretch.","Press onto your toes, pause, lower with control."],
      cue:"Keep the knees nearly straight. Skip if the rod area feels irritated."}},
    {n:"Lying leg raises", s:"3 × 12–15", tag:"core", g:{t:"Lower abs", r:"45s",
      steps:["Legs straight, lower back pressed down.","Lift to about 90°.","Lower without letting your back arch up."],
      cue:"Stop lowering where your back wants to lift."}},
    {n:"Dead bug", s:"2 × 12 / side", tag:"core", g:{t:"Deep core", r:"30s",
      steps:["Arms up, hips and knees at 90°, lower back flat.","Lower opposite arm and leg slowly.","Switch sides with control."],
      cue:"If your back lifts off the floor, shorten the reach."}},
  ]},
  { id:4, kind:"push", focus:"Push B", muscles:"Chest · Shoulders · Triceps", ex:[
    {n:"Flat dumbbell bench press", s:"3 × 8–12", g:{t:"Chest, front delts, triceps", r:"75s",
      steps:["Dumbbells at chest level, elbows ~45°.","Press up and slightly together, not locked out.","Lower to a stretch across the chest."],
      cue:"Shoulder blades pinned back into the bench the whole set."}},
    {n:"Arnold press", s:"3 × 10–12", g:{t:"Front + side delts", r:"70s",
      steps:["Dumbbells in front of shoulders, palms facing you.","Press up while rotating palms forward.","Reverse the rotation on the way down."],
      cue:"Smooth rotation, lighter weight than a straight press."}},
    {n:"Smith machine incline press", s:"3 × 10–12", g:{t:"Upper chest", r:"75s",
      steps:["Bench at 30–45°, bar at upper-chest height.","Lower under control to your upper chest.","Press to near-straight arms."],
      cue:"Same chest squeeze as the flat press, just aimed higher."}},
    {n:"Dumbbell lateral raises", s:"4 × 12–15", star:true, g:{t:"Side delts", r:"45s",
      steps:["Light dumbbells at your sides, slight forward lean.","Raise to shoulder height, leading with elbows.","Lower slowly, resisting all the way down."],
      cue:"Pinkie slightly higher than thumb. Light weight wins; drop the load if you're swinging."}},
    {n:"Seated dumbbell overhead triceps extension", s:"3 × 12–15", sub:"Two-arm", g:{t:"Triceps (long head)", r:"60s",
      steps:["Bench upright with back support; hold one dumbbell with both hands overhead.","Lower behind your head, upper arms close to your ears.","Extend back up, squeezing at the top."],
      cue:"The back pad blocks the arch; if your lower back lifts, go lighter. New pattern: keep it light for a couple of sessions. Single-arm is next month's level-up."}},
    {n:"Bench-supported triceps dips", s:"2 × 12–15", g:{t:"Triceps", r:"60s",
      steps:["Hands on the bench edge, hips off, legs extended.","Lower elbows to ~90°.","Press back to straight arms."],
      cue:"Elbows point back, hips stay close to the bench."}},
    {n:"Plank", s:"3 × 40 sec", tag:"core", g:{t:"Whole core", r:"45s",
      steps:["Forearms and toes, elbows under shoulders.","Straight line head to heels, glutes and abs braced."],
      cue:"Belly button pulled toward your spine, neck long."}},
    {n:"Bicycle crunches", s:"3 × 20", tag:"core", g:{t:"Abs, obliques", r:"45s",
      steps:["Knees up, hands lightly behind your head.","Rotate elbow to opposite knee, alternating sides."],
      cue:"Rotate from the ribs, not your neck."}},
  ]},
  { id:5, kind:"pull", focus:"Pull B", muscles:"Back · Rear delts · Biceps", ex:[
    {n:"Wide-grip lat pulldown", s:"3 × 10–12", sub:"or assisted pull-ups", g:{t:"Lats", r:"75s",
      steps:["Wide grip, slight lean back.","Pull to upper chest, elbows down and out.","Return to a full overhead stretch."],
      cue:"Bar stays in front, never behind the neck."}},
    {n:"T-bar row", s:"3 × 10–12", sub:"or supported barbell row", g:{t:"Mid-back", r:"75s",
      steps:["Chest supported, back flat ~45°.","Row to your stomach, squeezing the shoulder blades.","Lower to a full stretch."],
      cue:"Drive the elbows back; don't heave with the lower back."}},
    {n:"Dumbbell pullover", s:"3 × 12–15", g:{t:"Lats, serratus anterior, chest", r:"50s",
      steps:["Lie across a bench, upper back supported, hips low.","Holding one dumbbell with both hands, lower it back in a wide arc until you feel a stretch.","Pull back over your chest, driving through the lats."],
      cue:"Keep a slight elbow bend throughout; feel the stretch across your lats and ribs, not just your shoulders."}},
    {n:"Reverse pec-deck", s:"3 × 15, 12, 10", sub:"or rear-delt fly", g:{t:"Rear delts", r:"50s",
      steps:["Chest against the pad, soft elbow bend.","Open arms out and back in a wide arc.","Return slowly."],
      cue:"Small range, big squeeze; chest stays still."}},
    {n:"Seated dumbbell hammer curl", s:"2 × 10–12", g:{t:"Biceps, forearms", r:"45s",
      steps:["Seated, back supported, palms facing each other.","Curl together, neutral grip throughout.","Lower slowly."],
      cue:"Different grip from Day 2's curl for variety; same rule: no arching to finish a rep."}},
    {n:"Hanging knee raises", s:"3 × 12–15", tag:"core", g:{t:"Lower abs", r:"45s",
      steps:["Hang from a bar, brace to stop swinging.","Curl knees toward your chest.","Lower with control."],
      cue:"Curl the hips up, not just the thighs."}},
    {n:"Cable Pallof press", s:"3 × 12 / side", tag:"core", g:{t:"Obliques (anti-rotation)", r:"40s",
      steps:["Cable at chest height, stand sideways to the stack.","Press the handle straight out, resisting the pull to rotate.","Hold, then return under control."],
      cue:"Nothing moves but your arms; trains the obliques without twisting the spine."}},
  ]},
  { id:6, kind:"legs", focus:"Legs B: Quad/Ham + Glute", muscles:"knee-aware", ex:[
    {n:"Hack squat", s:"3 × 10–12", g:{t:"Quads, glutes", r:"90s",
      steps:["Back flat against the pad, feet hip-width.","Lower to a moderate depth with control.","Drive up through heels and midfoot."],
      cue:"Higher, wider stance is kinder to the knee. Swap to leg press if it complains."}},
    {n:"Dumbbell sumo RDL", s:"3 × 10–12", star:true, g:{t:"Glutes, hamstrings, adductors", r:"75s",
      steps:["Wide stance, toes out, dumbbells close to your legs.","Push hips back to a hamstring stretch.","Drive hips forward, squeezing glutes at the top."],
      cue:"A hinge, not a squat. Less forward knee travel than a regular squat, so it's knee-friendly."}},
    {n:"Lying leg curl", s:"3 × 12–15", sub:"or stability-ball curl", g:{t:"Hamstrings", r:"60s",
      steps:["Hips down on the pad.","Curl heels toward your glutes.","Lower slowly, nearly straight."],
      cue:"Watch the back of the left knee; keep the load moderate."}},
    {n:"Leg extension", s:"3 × 12–15", g:{t:"Quads", r:"60s",
      steps:["Pad on your lower shins, knees at the pivot.","Extend to lift, squeezing at the top.","Lower through a pain-free range."],
      cue:"Pause and squeeze at the top."}},
    {n:"Glute bridge or frog pump", s:"2 × 12–15", g:{t:"Glutes", r:"45s",
      steps:["Knees bent (or soles together for frog pump).","Drive hips up, squeezing hard at the top.","Lower with control."],
      cue:"Constant tension: short, strong squeezes."}},
    {n:"Standing calf raise", s:"2 × 15–20", sub:"Light", g:{t:"Gastrocnemius", r:"45s",
      steps:["Same setup as Day 3, lighter load."],
      cue:"Second weekly exposure for calf growth. Skip if the rod area feels irritated."}},
    {n:"Seated calf raise", s:"2–3 × 15–20", sub:"Gentle", g:{t:"Soleus", r:"45s",
      steps:["Balls of feet on the platform, pad over thighs.","Lower for a stretch, press up onto your toes."],
      cue:"Slow and gentle; start light."}},
    {n:"Low-impact HIIT", s:"10–15 min", tag:"finisher", g:{t:"Conditioning", r:"-",
      steps:["Bike, elliptical, or kettlebell swings: 30s hard / 30s easy."],
      cue:"Build from 5 rounds toward 7–8. No jumping."}},
  ]},
];
